### ISSUE TITLE
你好，我想问问，怎样在每个tab切换时加载不同的页面。我想实现这样的效果，就是每次切换tab，就会调用不同的数据???

### ISSUE THREAD

**Issue by zdlll** [naturezhm/swipeTab#1]

**Comment by zdlll** [comment]
如果你有时间，还麻烦你看看啊

**Comment by naturezhm** [comment]
@zdlll 在swipeTab.js里有个updateSelectedPage方法，在每次切换tab时都会调用，传入参数表示当前第几个tab，你需要调用不同数据，就可以将不同数据与这个page对应上来，比如第0个tab调用obj1，第1个tab调用obj2，至于是预先加载好，还是懒加载，根据需求来实现
